# Generated by Django 5.2 on 2025-05-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
