# Generated by Django 5.2 on 2025-05-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_blog_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quotes_author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
